/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 desk.glb --transform -t 
Files: desk.glb [256.54KB] > C:\Users\zeljk\OneDrive\Desktop\robot\desk w chair and acc\v2\desk-transformed.glb [30.78KB] (88%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane001: THREE.Mesh
    Plane001_1: THREE.Mesh
    Plane002: THREE.Mesh
    Plane002_1: THREE.Mesh
    Desk002: THREE.Mesh
    Chair001: THREE.Mesh
  }
  materials: {
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    PaletteMaterial007: THREE.MeshStandardMaterial
  }
}

export function Desk(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/desk-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.69, 1.046, 2.463]} rotation={[Math.PI / 2, 0, 0]} scale={0.488}>
        <mesh geometry={nodes.Plane001.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Plane001_1.geometry} material={materials.PaletteMaterial004} />
      </group>
      <group position={[0.098, 0.515, 2.738]} rotation={[Math.PI / 2, 0, 0]} scale={0.488}>
        <mesh geometry={nodes.Plane002.geometry} material={materials.PaletteMaterial005} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh geometry={nodes.Desk002.geometry} material={materials.PaletteMaterial006} position={[0.098, 0.515, 2.738]} rotation={[Math.PI / 2, 0, 0]} scale={0.488} />
      <mesh geometry={nodes.Chair001.geometry} material={materials.PaletteMaterial007} position={[0.124, 1.001, 3.54]} rotation={[Math.PI / 2, 0, -1.016]} scale={0.456} />
    </group>
  )
}

useGLTF.preload('/desk-transformed.glb')
